travis:
  secure:
    BINSTAR_TOKEN: TIkV3swhJBmnpCDzvaj0WwmO3ZqQ+7fY3cJSWcf/1byM5a0irl4OVfk83LR/VOPPSSHjfz5DdsAXYBqMjJYtPBXVRS5pwMaJGiQEcC1bRp13H1LlRd+T8rY/IVaNxvyZb7jN9V8SvSYoXXyGrNQTqhxbS12PBoS9ng47Mu5a0Pw+P12p83cyyJoOd1m+uVc202A5RjjMOVbUjAnAraFQfipzezOK3lJFFJDPZCkkHgi8XjP1w86dH+Ho93AUd1kHCWTD8aSxkuczZfU39DD6hXgplBWWJHU5xMcDv8eRpUd94mVQlSkkRjfxGN02DegaVDGrm7YtwoNecCQnBXeYQ9myhGWD6jU9whGTsoZ/Wyi6aCOK5GSP6f8m8EJSIBG3Wa8KtgfzzVEQPIHpYuhZy9XY1Y3y8Npsps9ynPJt3hLZoBqC29o7NcD9YriFf+qPxbKNkdmJiA8n2StS2w060zOIyTLGoK2E7ba6wbYoicXuGocYBcxDsTB4Dt+pn5CyUSF/AgUry53dhangC7Lx1K6mXx7DfuZFQaiWLy52epmKW/YRl6lnOQPJtsHazbm4YTWBXRvrZC65yMzgYvB9I4JX0J6+V8WX8TH2xAJnAoBrm2wltx+dQk1LanbDg4aDWXTY/PIePXA1KUN0w8KZwHNXRKg6ASsu4qZ9LUa1Su0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
