appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OG9F6B9Gi7u643k49/RoBJBIXKtclmjgXdrsaqztFeiFA7x8cUunqwnNYrelZka5qYflSOXV+ppV2cMFWY87I7mb6MBU0gvJAvE1i3olS7lKOeI9WmJQETlmepnUZ2FIp9SD4PUWUmAMvQgO+A14EfoCMCPcKUY94wO0ahd4ZLbMVpFFb1kYGPQi7WBOl4fqtprvQRsBZZYQZlMRND2oX+gdgw1F5QFKTk+AW3sgxXCURpvH+UJKjz4fIJti4bUKVc+njspWV7mAElRgcbuC3pRPIce487ZJ5Hal9yu2U1NeS4rgzrrgVq8TmaXNYhtRtdY9jx48y+NqlKYOVrWuObeho/NZsbqChDcO0hWMBCZvTafF7hzAPtuxt+lB5V4sZBhYO/H7WGH8DlRz/hzsq6w3OKjk7AwgVHHrP/fbd2SH6EavZ8Vd8Jcf9h8bK1S7bVPs0ssjtYt17TcNCMaD64mExeIVNfPYgH5Ag+wuxwc+7Sc/N3jGUUb8ZECVp9LM+X8ughMontkUK2CPnnEMbmcr29HuTkfKla6+iM29oBvaJ+JygpgREVu+NxnzKfEw6RQnyv4cDlJ0F4yzn5ixa2YGxlmlYxiIYl4rgouHklYlamgysQMihWxh625p9WC11IKhpNMkY403gBL+iQZsyq8gzS4FSGyJ30vpWMZk90U=}
